import { Tool } from './types';

export const TOOLS: Tool[] = [
  // 1. Essential Social Media Optimizers
  { id: 'ig-square', name: 'Instagram Square Post Resizer', category: 'Essential', description: 'Resize images to 1080x1080 square for Instagram.', icon: 'Instagram' },
  { id: 'yt-thumb', name: 'YouTube Thumbnail Safe-Zone Checker', category: 'Essential', description: 'Verify safe zones for text and thumbnails.', icon: 'Youtube' },
  { id: 'twitter-opt', name: 'Twitter (X) Header Optimizer', category: 'Essential', description: 'Optimize headers for X profiles.', icon: 'Twitter' },
  { id: 'linkedin-carousel', name: 'LinkedIn Carousel Splitter', category: 'Essential', description: 'Split images for LinkedIn carousels.', icon: 'Layout' },
  { id: 'tiktok-pfp', name: 'TikTok Profile Circle Cropper', category: 'Essential', description: 'Crop images for TikTok profile circles.', icon: 'CircleIcon' },
  { id: 'pinterest-pin', name: 'Pinterest Long Pin Maker', category: 'Essential', description: 'Create optimized 2:3 Pinterest pins.', icon: 'Pin' },
  { id: 'fb-cover', name: 'Facebook Cover Photo Previewer', category: 'Essential', description: 'Preview how your cover looks on FB.', icon: 'Facebook' },
  { id: 'thread-post', name: 'Thread Post Image Formatter', category: 'Essential', description: 'Format images for Threads.', icon: 'MessageSquare' },
  { id: 'whatsapp-status', name: 'WhatsApp Status Image Cropper', category: 'Essential', description: 'Crop for WhatsApp status updates.', icon: 'PhoneOutgoing' },
  { id: 'aspect-ratio', name: 'Image Aspect Ratio Changer', category: 'Essential', description: 'Change to 1:1, 4:5, 16:9, etc.', icon: 'Maximize' },
  { id: 'compressor', name: 'Bulk Image Compressor', category: 'Essential', description: 'Lossless compression for smaller file sizes.', icon: 'Minimize2' },
  { id: 'webp-converter', name: 'WebP to JPG Converter', category: 'Essential', description: 'Convert between WebP and JPG formats.', icon: 'RefreshCcw' },
  { id: 'svg-vectorizer', name: 'PNG to SVG Vectorizer', category: 'Essential', description: 'Basic vectorization for logos.', icon: 'Layers' },
  { id: 'heic-converter', name: 'HEIC to JPEG Converter', category: 'Essential', description: 'Convert iPhone photos to JPEG.', icon: 'Smartphone' },
  { id: 'base64-gen', name: 'Image to Base64 String Generator', category: 'Essential', description: 'Generate data URI strings.', icon: 'Code' },
  { id: 'dpi-changer', name: 'DPI Changer', category: 'Essential', description: 'Adjust DPI for print or web.', icon: 'Printer' },
  { id: 'grid-maker', name: 'Link in Bio Image Grid Maker', category: 'Essential', description: 'Create aesthetic grids for bio links.', icon: 'Grid' },
  { id: 'bg-extender', name: 'Story-to-Post Background Extender', category: 'Essential', description: 'Extend backgrounds for different formats.', icon: 'Expand' },
  { id: 'pfp-border', name: 'Profile Picture Border Ring Generator', category: 'Essential', description: 'Add colorful rings to profile pics.', icon: 'Circle' },
  { id: 'bg-remover', name: 'Transparent PNG Maker', category: 'Essential', description: 'Remove backgrounds using basic processing.', icon: 'Eraser' },

  // 2. Aesthetic & Branding Tools
  { id: 'palette', name: 'Palette Extractor', category: 'Aesthetic', description: 'Extract dominant colors from images.', icon: 'Palette' },
  { id: 'watermark', name: 'Minimalist Watermark Adder', category: 'Aesthetic', description: 'Add subtle text or logo watermarks.', icon: 'Stamp' },
  { id: 'noise', name: 'Aesthetic Grain/Noise Filter', category: 'Aesthetic', description: 'Add stylish film grain.', icon: 'CloudRain' },
  { id: 'duotone', name: 'Duo-tone Effect Generator', category: 'Aesthetic', description: 'Apply two-color gradients.', icon: 'Contrast' },
  { id: 'polaroid', name: 'Polaroid Frame Maker', category: 'Aesthetic', description: 'Add vintage polaroid borders.', icon: 'Frame' },
  { id: 'film-burn', name: 'Film Burn Overlay Tool', category: 'Aesthetic', description: 'Classic light leak effects.', icon: 'Zap' },
  { id: 'glassmorphism', name: 'Glassmorphism Effect Generator', category: 'Aesthetic', description: 'Apply frosty glass overlays.', icon: 'GlassWater' },
  { id: 'neumorphic', name: 'Neumorphic Shadow Adder', category: 'Aesthetic', description: 'Soft, tactile shadow effects.', icon: 'Box' },
  { id: 'rounded-corners', name: 'Image Border Radius Tool', category: 'Aesthetic', description: 'Add rounded corners easily.', icon: 'Square' },
  { id: 'gradient-overlay', name: 'Gradient Overlay Maker', category: 'Aesthetic', description: 'Apply smooth color transitions.', icon: 'Wind' },
  { id: 'vintage-suite', name: 'Vintage/Retro Filter Suite', category: 'Aesthetic', description: 'A collection of classic filters.', icon: 'History' },
  { id: 'bw-grader', name: 'Black & White Prof. Grader', category: 'Aesthetic', description: 'High-contrast monochrome edits.', icon: 'Moon' },
  { id: 'color-pop', name: 'Color Pop (Splash) Editor', category: 'Aesthetic', description: 'Keep one color, grey out the rest.', icon: 'Droplets' },
  { id: 'texture-overlay', name: 'Canvas Texture Overlay', category: 'Aesthetic', description: 'Add physical textures.', icon: 'Hammer' },
  { id: 'vignette', name: 'Vignette Effect Creator', category: 'Aesthetic', description: 'Darken edges for focus.', icon: 'Sun' },
  { id: 'tilt-shift', name: 'Tilt-Shift Blur Generator', category: 'Aesthetic', description: 'Create toy-like miniature effects.', icon: 'Focus' },
  { id: 'glitch', name: 'Image Glitch Effect', category: 'Aesthetic', description: 'Digital distortion aesthetics.', icon: 'Dna' },
  { id: 'pixel-art', name: 'Pixel Art Converter', category: 'Aesthetic', description: 'Retro 8-bit style conversion.', icon: 'Gamepad2' },
  { id: 'halftone', name: 'Halftone Pattern Maker', category: 'Aesthetic', description: 'Comic-book dot patterns.', icon: 'MoreHorizontal' },
  { id: 'modern-shadow', name: 'Modern Shadow/Reflection Creator', category: 'Aesthetic', description: 'Deep, realistic shadows.', icon: 'SunDim' },

  // 3. Text & Info-Graphic Tools
  { id: 'quote-maker', name: 'Quote Post Generator', category: 'Text', description: 'Beautifully style text quotes.', icon: 'Quote' },
  { id: 'tweet-mockup', name: 'Tweet to Image Mockup', category: 'Text', description: 'Convert text to X-style cards.', icon: 'Twitter' },
  { id: 'ig-thread', name: 'Instagram Thread Style Creator', category: 'Text', description: 'Thread-like vertical layouts.', icon: 'AlignLeft' },
  { id: 'text-overlay', name: 'Dynamic Text-on-Image', category: 'Text', description: 'Advanced typography placement.', icon: 'Type' },
  { id: 'meme-gen', name: 'Meme Generator', category: 'Text', description: 'Classic and modern templates.', icon: 'Laugh' },
  { id: 'vs-maker', name: 'Comparison/Versus Maker', category: 'Text', description: 'Side-by-side split screens.', icon: 'Columns' },
  { id: 'tutorial-card', name: 'Step-by-Step Tutorial Maker', category: 'Text', description: 'Create visual instructional cards.', icon: 'CheckSquare' },
  { id: 'percentage-chart', name: 'Percentage Chart Image Gen', category: 'Text', description: 'Visualize data as infographics.', icon: 'PieChart' },
  { id: 'rating-card', name: 'Rating Star/Review Card Maker', category: 'Text', description: 'Generate review testimonials.', icon: 'Star' },
  { id: 'news-template', name: 'News Headline Generator', category: 'Text', description: 'Breaking news style graphics.', icon: 'Newspaper' },
  { id: 'carbon-code', name: 'Code Snippet to Image', category: 'Text', description: 'Beautiful syntax highlighting snapshots.', icon: 'Code2' },
  { id: 'subtitle-adder', name: 'Subtitle Style Text Adder', category: 'Text', description: 'Cinematic caption overlays.', icon: 'Minus' },
  { id: 'price-tag', name: 'Price Tag/Offer Badge Overlay', category: 'Text', description: 'Sales and discount badges.', icon: 'Tag' },
  { id: 'cta-maker', name: 'Call-to-Action Button Maker', category: 'Text', description: 'Generate clickable-look buttons.', icon: 'MousePointer2' },
  { id: 'faq-card', name: 'FAQ Card Creator', category: 'Text', description: 'Question and answer layouts.', icon: 'HelpCircle' },
  { id: 'testimonial-gen', name: 'Testimonial Image Generator', category: 'Text', description: 'Social proof graphics.', icon: 'Users' },
  { id: 'disclaimer-maker', name: 'Disclaimer/Warning Label', category: 'Text', description: 'Add official looking labels.', icon: 'AlertTriangle' },
  { id: 'vertical-text', name: 'Vertical Text Creator', category: 'Text', description: 'Story-optimized vertical fonts.', icon: 'ArrowDownNarrowWide' },
  { id: 'neon-text', name: 'Neon Sign Text Effect', category: 'Text', description: 'Glowy retro neon sign styles.', icon: 'Lightbulb' },
  { id: 'handwriting', name: 'Handwriting Overlay Generator', category: 'Text', description: 'Organic scribbled text look.', icon: 'PenTool' },

  // 4. Technical & Utility Tools
  { id: 'exif-remover', name: 'Image Metadata (EXIF) Remover', category: 'Technical', description: 'Strip privacy-sensitive data.', icon: 'ShieldOff' },
  { id: 'qr-gen', name: 'QR Code Generator', category: 'Technical', description: 'Create QR codes with logo support.', icon: 'QrCode' },
  { id: 'barcode-maker', name: 'Barcode Maker', category: 'Technical', description: 'Generate standard barcodes.', icon: 'Barcode' },
  { id: 'magnifier', name: 'Image Magnifier Zoom Creator', category: 'Technical', description: 'Highlight specific image details.', icon: 'Search' },
  { id: 'before-after', name: 'Comparison Slider Generator', category: 'Technical', description: 'Interactive before/after views.', icon: 'Diff' },
  { id: 'mirror-flip', name: 'Image Mirror/Flip Tool', category: 'Technical', description: 'Reverse images horizontally/vertically.', icon: 'FlipHorizontal' },
  { id: 'pano-viewer', name: '360° Panorama Viewer', category: 'Technical', description: 'Navigate panoramas in-browser.', icon: 'Globe' },
  { id: 'histogram', name: 'Image Histogram Analyzer', category: 'Technical', description: 'Visualize color distribution.', icon: 'BarChart' },
  { id: 'dominant-color', name: 'Dominant Color Identifier', category: 'Technical', description: 'Find the primary tones.', icon: 'Pipette' },
  { id: 'tiler', name: 'Image Tiler (Pattern Maker)', category: 'Technical', description: 'Create repeating patterns.', icon: 'Repeat' },
  { id: 'sprite-sheet', name: 'Sprite Sheet Generator', category: 'Technical', description: 'Packing images for development.', icon: 'Table' },
  { id: 'gif-frames', name: 'GIF to Frames Extractor', category: 'Technical', description: 'Deconstruct animations into stills.', icon: 'FastForward' },
  { id: 'encryptor', name: 'Image Encryptor/Decryptor', category: 'Technical', description: 'Hide secret messages in pixels.', icon: 'Key' },
  { id: 'screenshot-mockup', name: 'Screenshot Mockup Wrapper', category: 'Technical', description: 'Place screenshots into device frames.', icon: 'Monitor' },
  { id: 'batch-rename', name: 'Batch Rename Utility', category: 'Technical', description: 'Organize files systematically.', icon: 'FileText' },
  { id: 'size-estimator', name: 'File Size Estimator', category: 'Technical', description: 'Predict output size before export.', icon: 'HardDrive' },
  { id: 'color-blindness', name: 'Color Blindness Simulator', category: 'Technical', description: 'Verify accessibility contrast.', icon: 'Eye' },
  { id: 'rule-of-thirds', name: 'Rule of Thirds Overlay', category: 'Technical', description: 'Compositional guidance grid.', icon: 'Hash' },
  { id: 'blur-sensitive', name: 'Blur/Pixelate Sensitive Info', category: 'Technical', description: 'Obscure faces or numbers.', icon: 'Ghost' },
  { id: 'filter-suite', name: 'Image Adjustments Suite', category: 'Technical', description: 'Brightness, contrast, and saturation.', icon: 'Sliders' },

  // 5. Advanced & Creative Tools
  { id: 'ascii-art', name: 'ASCII Art Generator', category: 'Creative', description: 'Convert images to text symbols.', icon: 'Terminal' },
  { id: 'low-poly', name: 'Image to Low-Poly Art', category: 'Creative', description: 'Geometric triangulation style.', icon: 'Triangle' },
  { id: 'kaleidoscope', name: 'Kaleidoscope Pattern Maker', category: 'Creative', description: 'Symmetrical fractal aesthetics.', icon: 'SunMedium' },
  { id: 'oil-painting', name: 'Oil Painting Effect', category: 'Creative', description: 'Artistic brushstroke simulation.', icon: 'Brush' },
  { id: 'sketch-converter', name: 'Sketch/Line Art Converter', category: 'Creative', description: 'Pencil drawing style.', icon: 'Pencil' },
  { id: 'double-exposure', name: 'Double Exposure Maker', category: 'Creative', description: 'Merge two images for depth.', icon: 'Blend' },
  { id: 'motion-blur', name: 'Motion Blur Simulator', category: 'Creative', description: 'Add kinetic energy to stills.', icon: 'Wind' },
  { id: 'sphere-projection', name: 'Sphere/Globe Projection', category: 'Creative', description: 'Wrap images around 3D spheres.', icon: 'Dribbble' },
  { id: 'distortion', name: 'Image Distortion (Warp)', category: 'Creative', description: 'Manipulate pixel perspectives.', icon: 'VenetianMask' },
  { id: 'hue-shift', name: 'Color Replacement (Hue)', category: 'Creative', description: 'Targeted color swapping.', icon: 'Eraser' },
  { id: 'perspective-wrapper', name: 'Perspective Wrapper', category: 'Creative', description: 'Place images on angled planes.', icon: 'Cuboid' },
  { id: 'collage-maker', name: 'Photo Collage Maker', category: 'Creative', description: 'Auto-grid collage logic.', icon: 'GanttChartSquare' },
  { id: 'mosaic', name: 'Image Mosaic Creator', category: 'Creative', description: 'Built from thousands of small tiles.', icon: 'Trello' },
  { id: 'pop-art', name: 'Pop Art Maker', category: 'Creative', description: 'Bold Andy Warhol style repeats.', icon: 'Sparkles' },
  { id: 'silhouette', name: 'Silhouette Creator', category: 'Creative', description: 'Solid black subject mapping.', icon: 'UserCircle' },
  { id: 'auto-fill', name: 'Background Color Auto-Fill', category: 'Creative', description: 'Edge-matching color extension.', icon: 'PaintBucket' },
  { id: 'inverter', name: 'Image Inverter', category: 'Creative', description: 'Reverse all pixel colors.', icon: 'Divide' },
  { id: 'smart-crop', name: 'Smart Crop (Saliency)', category: 'Creative', description: 'AI-free focus point cropping.', icon: 'Crop' },
  { id: 'batch-exporter', name: 'Multi-format Batch Exporter', category: 'Creative', description: 'Export all formats at once.', icon: 'FileUp' },
  { id: 'mobile-optimizer', name: 'Image Optimizer for Mobile', category: 'Creative', description: 'Ultra-fast loading formats.', icon: 'ZapOff' },
];

export const CATEGORIES: ToolCategory[] = ['Essential', 'Aesthetic', 'Text', 'Technical', 'Creative'];
